### ISSUE TITLE
Add Circle Shape

### ISSUE THREAD

**Issue by ishandeveloper** [DSC-ChitkaraUniv/Git-For-Freshers#2]
### Add the circle shape as shown in repository's README.

Use these parameters for styling : 

**Size** : 120px x 120px
**Color** : #0000ff

Make sure to switch to a different branch before commiting your changes.

**Comment by priyanshu0085984** [comment]
I am intersted in this task.May i work on it.

**Comment by ishandeveloper** [comment]
Hey @priyanshu0085984, I can see you've already made a PR, I'll review it now. 

Thank you for your contribution : )
