### ISSUE TITLE
Add Triangle Shape

### ISSUE THREAD

**Issue by ishandeveloper** [DSC-ChitkaraUniv/Git-For-Freshers#3]
### Add the triangle shape as shown in repository's README.

Use these parameters for styling : 

**Size** : 120px x 120px
**Color** : #008000

Make sure to switch to a different branch before commiting your changes.

**Comment by aditya28sarin** [comment]
Can you assign the issue to me?

**Comment by ishandeveloper** [comment]
Hey @aditya28sarin Thank you for showing your enthusiasm towards making an open-source contribution. However, I'm really sorry I won't be able to assign this issue to you, as this repository is meant as a practice task for some new internal collaborators. 

Feel free to explore other repositories and I would love to help you in any way possible, if i can : )

**Comment by shrutigoela** [comment]
I'd like to work on this issue can you assign this to me?

**Comment by ishandeveloper** [comment]
Sure, @shrutigoela . Go ahead and make a PR.
