### ISSUE TITLE
Add Egg Shape

### ISSUE THREAD

**Issue by ishandeveloper** [DSC-ChitkaraUniv/Git-For-Freshers#4]
### Add the egg shape as shown in repository's README.

Use these parameters for styling : 

**Size** : 94px x 120px
**Color** : #ff0000

Make sure to switch to a different branch before commiting your changes.

**Comment by aditya28sarin** [comment]
Can you assign the issue to me?

**Comment by gryfinlord** [comment]
Can you assign the issue to me? (Issue#4)

**Comment by ishandeveloper** [comment]
@gryfinlord Sure, please go ahead : )

@aditya28sarin Please refer to [this](https://github.com/DSC-ChitkaraUniv/Git-For-Freshers/issues/3#issuecomment-771535099)
