### ISSUE TITLE
Add Diamond Shape

### ISSUE THREAD

**Issue by ishandeveloper** [DSC-ChitkaraUniv/Git-For-Freshers#5]
### Add the diamond shape as shown in repository's README.

Use these parameters for styling : 

**Size** : 120px x 120px
**Color** : #ff1493

Make sure to switch to a different branch before commiting your changes.

**Comment by aditya28sarin** [comment]
Can you assign the issue to me?

**Comment by gryfinlord** [comment]
Can you Assign the issue to me..

**Comment by ishandeveloper** [comment]
@aditya28sarin kindly refer to [this](https://github.com/DSC-ChitkaraUniv/Git-For-Freshers/issues/3#issuecomment-771535099)

**Comment by bhaveshgoyal182** [comment]
This seems to be interesting, can you assign this issue to me?

**Comment by ishandeveloper** [comment]
I'm really sorry @bhaveshgoyal182 , but these issues are only meant for the freshers of our university. I hope you understand. 

Feel free to look for issues created in other repositories or just create a new one, if you find anything that needs to be fixed, and I'll assign that to you : )

### Happy Coding ✨

**Comment by sanchitpasricha** [comment]
can you assign this issue to me ?

**Comment by ishandeveloper** [comment]
Please go ahead @sanchitpasricha
