### ISSUE TITLE
Add semi-circle shape

### ISSUE THREAD

**Issue by ishandeveloper** [DSC-ChitkaraUniv/Git-For-Freshers#6]
### Add the semi-circle shape as shown in repository's README.

Use these parameters for styling : 

**Size** : 60px x 120px
**Color** : #000000

Make sure to switch to a different branch before commiting your changes.

**Comment by aditya28sarin** [comment]
Can you assign the issue to me?

**Comment by ishandeveloper** [comment]
Again, kindly refer to [this](https://github.com/DSC-ChitkaraUniv/Git-For-Freshers/issues/3#issuecomment-771535099), @aditya28sarin

**Comment by talkishita** [comment]
I'd like to work on this issue can you assign me this issue?

**Comment by ishandeveloper** [comment]
Sure @talkishita , Please go ahead : )
